### ISSUE TITLE
IndexError: cannot do a non-empty take from an empty axes.

### ISSUE THREAD

**Issue by sYnfo** [ecbftw/nanown#5]
I'm getting this error when running ```./train test.db``` with numpy==1.9.2. Traceback:

Traceback (most recent call last):
  File "./train", line 166, in <module>
    unusual_case,delta = findUnusualTestCase(db)
  File "/home/mstuchli/nanown/trunk/bin/../lib/nanownlib/__init__.py", line 369, in findUnusualTestCase
    global_tm = quadsummary([row['packet_rtt'] for row in cursor])
  File "/home/mstuchli/nanown/trunk/bin/../lib/nanownlib/stats.py", line 185, in quadsummary
    l1,l2,r2,r1 = numpy.percentile(values, (left1,left2,right2,right1))
  File "/usr/lib64/python3.4/site-packages/numpy/lib/function_base.py", line 3054, in percentile
    interpolation=interpolation)
  File "/usr/lib64/python3.4/site-packages/numpy/lib/function_base.py", line 2803, in _ureduce
    r = func(a, **kwargs)
  File "/usr/lib64/python3.4/site-packages/numpy/lib/function_base.py", line 3143, in _percentile
    x1 = take(ap, indices_below, axis=axis) * weights_below
  File "/usr/lib64/python3.4/site-packages/numpy/core/fromnumeric.py", line 121, in take
    return take(indices, axis, out, mode)
IndexError: cannot do a non-empty take from an empty axes.

Any idea what the problem could be? I can try to upload the db somewhere, if necessary.

**Comment by ecbftw** [comment]
Thanks for the report.

This exception comes up when `quadsummary` is fed no data.  This is typically because something didn't record properly during the data collection phase.  At this step, it is trying to make preliminary estimates  of time differences based on the `packet_rtt` times. Did you run the data collection as `root` (or with privileges to sniff the network)?

**Comment by sYnfo** [comment]
As root, correct. I did ```python3 sampler train 50000 w.x.y.z -c '{"short": "X", "long": "DEADBEEF"}'```.

**Comment by ecbftw** [comment]
Sorry for the slow reply.  Will have more time next week.

I'm happy to look at the database you have.  It would also be helpful to see your customized sampler script, perhaps with key site details removed.

I just sent you a direct message on twitter with my contact details.

**Comment by ecbftw** [comment]
The project is moving off of GitHub.  If you still want help with this, please submit a ticket here:
  https://code.blindspotsecurity.com/trac/nanown/newticket

Thanks!
